const data = [
    {
        id:60011,
        name:"آزمون مداد کاغذی فصل 2 کسر ریاضی",
        caption:"آزمون مداد کاغذی فصل 2 کسر ریاضی - ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/آزمون-مداد-کاغذی-فصل-2-کسر-ریاضی-(سری2)-ششم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/riazi.jpg",
        slug: "/sheshom/soalat/60011"
    } , 
    {
        id:60012,
        name:"تمرین فصل 3 اعداد اعشاری ریاضی",
        caption:"تمرین فصل 3 اعداد اعشاری ریاضی - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/تمرین-فصل-3-اعداد-اعشاری-ریاضی-(سری1)-ششم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/riazi.jpg",
        slug: "/sheshom/soalat/60012"
    } , 
    {
        id:60013,
        name:"نمونه سوال درس 4 سفر به اعماق زمین علوم تجربی با پاسخ",
        caption:"نمونه سوال درس 4 سفر به اعماق زمین علوم تجربی با پاسخ - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوال-درس-4-سفر-به-اعماق-زمین-علوم-تجربی-(سری1)-ششم-دبستان.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/oloom.jpg",
        slug: "/sheshom/soalat/60013"
    } , 
    {
        id:60014,
        name:"نمونه سوال درس 1-2-3-4 علوم تجربی",
        caption:"نمونه سوال درس 1-2-3-4 علوم تجربی - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوال-درس-1-2-3-4-علوم-تجربی-(سری1)-ششم-دبستان.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/oloom.jpg",
        slug: "/sheshom/soalat/60014"
    } , 
    {
        id:60015,
        name:"آزمون درس 1 تا 5 فارسی",
        caption:"آزمون درس 1 تا 5 فارسی - پایه ششم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/آزمون-درس-1-تا-5-فارسی-(سری3)-ششم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/farsi.jpg",
        slug: "/sheshom/soalat/60015"
    } , 
    {
        id:60016,
        name:"نمونه سوال درس 3 و 4 فارسی",
        caption:"نمونه سوال درس 3 و 4 فارسی - پایه ششم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه سوال درس 3 و 4 فارسی.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/farsi.jpg",
        slug: "/sheshom/soalat/60016"
    } , 
    {
        id:60017,
        name:"آزمون درس 5-6-7-8 مطالعات اجتماعی",
        caption:"آزمون درس 5-6-7-8 مطالعات اجتماعی - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/آزمون-درس-5-6-7-8-مطالعات-اجتماعی-(سری2)-ششم-دبستان.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/motaleat.jpg",
        slug: "/sheshom/soalat/60017"
    } , 
    {
        id:60018,
        name:"آزمون مداد کاغذی درس 1 تا 6 مطالعات اجتماعی",
        caption:"آزمون مداد کاغذی درس 1 تا 6 مطالعات اجتماعی - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/آزمون-مداد-کاغذی-درس-1-تا-6-مطالعات-اجتماعی-(سری2)-ششم-دبستان.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/motaleat.jpg",
        slug: "/sheshom/soalat/60018"
    } , 
    {
        id:60019,
        name:"نمونه سوال نوبت اول قرآن",
        caption:"نمونه سوال نوبت اول قرآن - پایه ششم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوال-نوبت-اول-قرآن-(سری4)-ششم-دبستان.pdf",
        book:"quran",
        boolInP:"آموزش قرآن",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/quran.jpg",
        slug: "/sheshom/soalat/60019"
    } , 
    {
        id:60020,
        name:"نمونه سوالات درس 1 تا 14 قرآن ",
        caption:"نمونه سوالات درس 1 تا 14 قرآن - پایه ششم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوالات-درس-1-تا-14-قرآن-(سری1)-ششم-دبستان.pdf",
        book:"quran",
        boolInP:"آموزش قرآن",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/quran.jpg",
        slug: "/sheshom/soalat/60020"
    } , 
    {
        id:60021,
        name:"نمونه سوال درس 1-2-3-4 هدیه های آسمان با پاسه",
        caption:"نمونه سوال درس 1-2-3-4 هدیه های آسمان - پایه ششم - با پاسخنامه",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوال-درس-1-2-3-4-هدیه-های-آسمان-(سری-2)-ششم-ابتدایی.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/hedye.jpg",
        slug: "/sheshom/soalat/60021"
    } , 
    {
        id:60022,
        name:"نمونه سوال درس 4 باغ سری هدیه های آسمانی",
        caption:"نمونه سوال درس 4 باغ سری هدیه های آسمانی - پایه ششم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/sheshom/soalat/نمونه-سوال-درس-4-باغ-سری-هدیه-های-آسمانی-با-پاسخ-(سری3)-ششم-دبستان.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه ششم",
        image:"/images/components/modules/books/sheshom/hedye.jpg",
        slug: "/sheshom/soalat/60022"
    } , 
    

]

export default data