const data = [
    {
        id:40011,
        name:"آزمون مستمر مهر ماه ریاضی چهارم",
        caption:"آزمون مستمر ریاضی پایه چهارم، از فصل 1، مهر ماه",
        creator:"محمد لبافی",
        upoledDate:"1403/07/27",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/ارزیابی مهر ماه ریاضی (1).pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40011"
    } , 
    {
        id:40012,
        name:"ارزیابی مهر ماه مطالعات اجتماعی",
        caption:"ارزیابی مهر ماه مطالعات اجتماعی - پایه چهارم - دروس 1 و 2 و 3",
        creator:"سید حسین قریشیان",
        upoledDate:"1403/07/27",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/ارزیابی مهر ماه مطالعات اجتماعی (1).pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/motaleat.jpg",
        slug: "/chaharom/soalat/40012"
    } ,
    {
        id:40013,
        name:"ارزشیابی علوم مهرماه - پایه چهارم",
        caption:"ارزشیابی علوم مهرماه - پایه چهارم - دروس 1 و 2",
        creator:"یونس علمداری",
        upoledDate:"1403/07/26",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/علوم مهر ماه.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/oloom.jpg",
        slug: "/chaharom/soalat/40013"
    } ,
    {
        id:40014,
        name:"ارزشیابی علوم آبان ماه - پایه چهارم",
        caption:"ارزشیابی علوم مهرماه - پایه چهارم - دروس 1 و 2",
        creator:"یونس علمداری",
        upoledDate:"1403/08/29",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/آبان علوم.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/oloom.jpg",
        slug: "/chaharom/soalat/40014"
    } ,
    {
        id:40015,
        name:"ارزیابی آبان ماه مطالعات اجتماعی",
        caption:"ارزیابی آبان ماه مطالعات اجتماعی - پایه چهارم - دروس 4 و 5 و 6",
        creator:"سید حسین قریشیان",
        upoledDate:"1403/08/28",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/1_14988644601.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/motaleat.jpg",
        slug: "/chaharom/soalat/40015"
    } ,
    {
        id:40016,
        name:"آزمون مستمر آبان ماه ریاضی چهارم",
        caption:"آزمون مستمر ریاضی پایه چهارم، از فصل 1 و 2، آبان ماه",
        creator:"محمد لبافی",
        upoledDate:"1403/08/29",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/ارزیابی آبان ماه ریاضی (1).pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40016"
    } ,
    {
        id:40017,
        name:"ارزیابی ماهانه هدیه های آسمانی از درس ۱ تا ۴",
        caption:"ارزیابی ماهانه هدیه های آسمانی از درس ۱ تا ۴ - پایه چهارم",
        creator:"سید حسین قریشیان",
        upoledDate:"1403/08/29",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/ارزیابی ماهانه هدیه های آسمانی.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/hedye.jpg",
        slug: "/chaharom/soalat/40017"
    } 
    ,
    {
        id:40018,
        name:"ارزیابی ماهانه فارسی از درس 1 تا 5",
        caption:"ارزیابی ماهانه فارسی از درس 1 تا 5 - پایه چهارم",
        creator:"یونس علمداری",
        upoledDate:"1403/08/28",
        fileType:"PDF",
        src:"/Files/chaharom/soalat/نگارش  آبان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/farsi.jpg",
        slug: "/chaharom/soalat/40018"
    }
    ,
    {
        id:40019,
        name:"تمرین فصل 1 و 2 ریاضی — چهارم دبستان",
        caption:"تمرین فصل 1 و 2 ریاضی — چهارم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"https://biamoz.com/dl/4/riazi/f2/%D8%AA%D9%85%D8%B1%DB%8C%D9%86-%D9%81%D8%B5%D9%84-1-%D9%88-2-%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C-(%D8%B3%D8%B1%DB%8C2)-%DA%86%D9%87%D8%A7%D8%B1%D9%85-%D8%AF%D8%A8%D8%B3%D8%AA%D8%A7%D9%86_Biamoz.com.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40019"
    }
    ,
    {
        id:40020,
        name:"آزمون مداد کاغذی و عملکردی فصل 1 و 2 ریاضی — چهارم دبستان",
        caption:"آزمون مداد کاغذی و عملکردی فصل 1 و 2 ریاضی — چهارم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"https://biamoz.com/dl/4/riazi/f2/%D8%A2%D8%B2%D9%85%D9%88%D9%86-%D9%85%D8%AF%D8%A7%D8%AF-%DA%A9%D8%A7%D8%BA%D8%B0%DB%8C-%D9%88-%D8%B9%D9%85%D9%84%DA%A9%D8%B1%D8%AF%DB%8C-%D9%81%D8%B5%D9%84-1-%D9%88-2-%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C-(%D8%B3%D8%B1%DB%8C1)-%DA%86%D9%87%D8%A7%D8%B1%D9%85-%D8%AF%D8%A8%D8%B3%D8%AA%D8%A7%D9%86_Biamoz.com.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40020"
    },
    {
        id:40021,
        name:"نمونه سوال و حل تمرین فصل 1 و 2 ریاضی",
        caption:"نمونه سوال و حل تمرین فصل 1 و 2 ریاضی — چهارم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"https://biamoz.com/dl/4/riazi/f2/%D8%AA%D9%85%D8%B1%DB%8C%D9%86-%D9%81%D8%B5%D9%84-1-%D9%88-2-%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C-(%D8%B3%D8%B1%DB%8C1)-%DA%86%D9%87%D8%A7%D8%B1%D9%85-%D8%AF%D8%A8%D8%B3%D8%AA%D8%A7%D9%86_Biamoz.com.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40021"
    },
    {
        id:40022,
        name:"ارزشیابی مستمر فصل 2 کسر ریاضی",
        caption:"ارزشیابی مستمر فصل 2 کسر ریاضی — چهارم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/09/03",
        fileType:"PDF",
        src:"https://biamoz.com/dl/4/riazi/f2/%D8%A7%D8%B1%D8%B2%D8%B4%DB%8C%D8%A7%D8%A8%DB%8C-%D9%85%D8%B3%D8%AA%D9%85%D8%B1-%D9%81%D8%B5%D9%84-2-%DA%A9%D8%B3%D8%B1-%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C-(%D8%B3%D8%B1%DB%8C1)-%DA%86%D9%87%D8%A7%D8%B1%D9%85-%D8%AF%D8%A8%D8%B3%D8%AA%D8%A7%D9%86_Biamoz.com.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه چهارم",
        image:"/images/components/modules/books/chaharom/riazi.jpg",
        slug: "/chaharom/soalat/40022"
    }

]

export default data