const data = [
    {
        id:50011,
        name:"نمونه سوال فصل 1 و 2 ریاضی با پاسخ",
        caption:"نمونه سوال فصل 1 و 2 ریاضی با پاسخ — پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-1-و-2-ریاضی-با-پاسخ-(سری1)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50011"
    } , 
    {
        id:50012,
        name:"نمونه سوال فصل 3 نسبت تناسب و درصد ریاضی",
        caption:"نمونه سوال فصل 3 نسبت تناسب و درصد ریاضی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-3-نسبت-تناسب-و-درصد-ریاضی-(سری13)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50012"
    } , 
    {
        id:50013,
        name:"نمونه سوال فصل 1-2-3 ریاضی",
        caption:"نمونه سوال فصل 1-2-3 ریاضی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-1-2-3-ریاضی-(سری8)-پنجم-دبستان.pdf",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/riazi.jpg",
        slug: "/panjom/soalat/50013"
    } , 
    {
        id:50014,
        name:"نمونه سوال درس1-2-3 علوم تجربی",
        caption:"نمونه سوال درس1-2-3 علوم تجربی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس1-2-3-علوم-تجربی-(سری2)-پنجم-دبستان.pdf",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/oloom.jpg",
        slug: "/panjom/soalat/50014"
    } , 
    {
        id:50015,
        name:"نمونه سوال درس 1 تا 5 فارسی",
        caption:"نمونه سوال درس 1 تا 5 فارسی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-1-تا-5-فارسی-(سری3)-پنجم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/soalat/50015"
    } , 
    {
        id:50016,
        name:"آزمون املا درس 3 رازی و ساخت بیمارستان",
        caption:"آزمون املا درس 3 رازی و ساخت بیمارستان - فارسی پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/آزمون-املا-درس-3-رازی-و-ساخت-بیمارستان-فارسی-(سری3)-پنجم-دبستان.pdf",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/farsi.jpg",
        slug: "/panjom/soalat/50016"
    } , 
    {
        id:50017,
        name:"آزمون مداد کاغذی درس 1-2-3-4 مطالعات اجتماعی",
        caption:"آزمون مداد کاغذی درس 1-2-3-4 مطالعات اجتماعی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"WORD",
        src:"/Files/panjom/soalat/آزمون-مداد-کاغذی-درس-1-2-3-4-مطالعات-اجتماعی-(سری1)-پنجم-دبستان.docx",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/soalat/50017"
    } , 
    {
        id:50018,
        name:"پرسش و پاسخ درس 3 هدیه های آسمانی",
        caption:"پرسش و پاسخ درس 3 هدیه های آسمانی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/20",
        fileType:"PDF",
        src:"/Files/panjom/soalat/پرسش-و-پاسخ-درس-3-........-هدیه-های-آسمانی-(سری1)-پنجم-دبستان.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/hedye.jpg",
        slug: "/panjom/soalat/50018"
    } , 
    {
        id:50019,
        name:"نمونه سوال درس 2 و 3 هدیه های آسمانی",
        caption:"نمونه سوال درس 2 و 3 هدیه های آسمانی - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-2-و-3-هدیه-های-آسمانی-(سری3)-پنجم-دبستان.pdf",
        book:"hedye",
        boolInP:"هدیه های آسمان",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/hedye.jpg",
        slug: "/panjom/soalat/50019"
    } ,
    {
        id:50020,
        name:"آزمون عملکردی درس 1-2-3-4 قرآن",
        caption:"آزمون عملکردی درس 1-2-3-4 قرآن - پایه پنجم",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/آزمون-عملکردی-درس-1-2-3-4-قرآن-(سری1)-پنجم-دبستان.pdf",
        book:"quran",
        boolInP:"قرآن",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/quran.jpg",
        slug: "/panjom/soalat/50020"
    } , 
    {
        id:50021,
        name:"نمونه سوال درس 1 تا 5 قرآن",
        caption:"نمونه سوال درس 1 تا 5 قرآن - پنجم دبستان",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-درس-1-تا-5-قرآن-پنجم-ابتدایی.pdf",
        book:"quran",
        boolInP:"آموزش قرآن",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/quran.jpg",
        slug: "/panjom/soalat/50021"
    } , 
    {
        id:50022,
        name:"نمونه سوال فصل 2 درس 5 مطالعات اجتماعی ",
        caption:"نمونه سوال فصل 2 درس 5 مطالعات اجتماعی — پنجم ابتدایی",
        creator:"محمد لبافی",
        upoledDate:"1403/08/23",
        fileType:"PDF",
        src:"/Files/panjom/soalat/نمونه-سوال-فصل-2-درس-5-مطالعات-اجتماعی-پنجم-ابتدایی.pdf",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه پنجم",
        image:"/images/components/modules/books/panjom/motaleat.jpg",
        slug: "/panjom/soalat/50022"
    } , 
    
    

]

export default data